// <autogenerated>
//   This file was generated by T4 code generator Reps.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using LM.Core.Data.Initializers;
using LM.Core.Infrastructure;
using LM.Core.Data.Migrations.Migrations;

namespace LM.Data.Infrastructure
{
	 public partial class CreateDatabaseIfNotExistsWithSeedLMReadContext :CreateDatabaseIfNotExistsWithSeedBase<LMReadContext>
    {
       
        public CreateDatabaseIfNotExistsWithSeedLMReadContext()
        {
            SeedActions.Add(new CreateDatabaseSeedAction());
        }
		
          
       }
} 
           
