// <autogenerated>
//   This file was generated by T4 code generator Reps.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using LM.Core.Data.Initializers;
using LM.Core.Infrastructure;
using LM.Core.Infrastructure.DependencyManagement;
using System.Data.Entity;
using Autofac;

namespace LM.Data.Infrastructure
{
	 public partial class DependencyRegistrar :IDependencyRegistrar
    {
       
       
	 	  public virtual void Register(ContainerBuilder builder, ITypeFinder typeFinder)
            {
      			 builder.RegisterType<LMReadContext>().As<DbContext>()
               .PropertiesAutowired()
              .InstancePerLifetimeScope().Keyed<DbContext>("LMReadContext");
		
	     			 builder.RegisterType<LMWriteContext>().As<DbContext>()
               .PropertiesAutowired()
              .InstancePerLifetimeScope().Keyed<DbContext>("LMWriteContext");
		
	                
           
        }
		 public int Order
        {
            get
            {
                return 1;
            }
        }

          
       }
} 
           
