// <autogenerated>
//   This file was generated by T4 code generator Reps.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using LM.Core.Data.Initializers;
using LM.Core.Infrastructure;
using LM.Core.Data;
using LM.Data.Models;

namespace LM.Data.Infrastructure
{
	 public partial interface ILMRepCollection : IDbSession
    {
       
         			IRepository<ApprovalType> ApprovalType{get;}
		
	               
     }
} 
           
