// <autogenerated>
//   This file was generated by T4 code generator Reps.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using LM.Core.Data.Initializers;
using LM.Core.Infrastructure;
using LM.Core.Data;
using LM.Data.Models;
using System.Data.Entity;
using Autofac;

namespace LM.Data.Infrastructure
{
	 public partial class LMReadContextRepCollection :DbSessionBase, IDbSession
    {
        protected override void SetDbContext()
        {
            _db = EngineContext.Current.ResolveKeyed<DbContext>("LMReadContext");
        }
         			private IRepository<ApprovalType> _ApprovalType = null;
			public IRepository<ApprovalType> ApprovalType
			{
			get{
			  if(_ApprovalType == null)
			  {
			    _ApprovalType = EngineContext.Current.Resolve<IRepository<ApprovalType>>(new NamedParameter("db", _db));
				return _ApprovalType;
			  }
			  return _ApprovalType;
			}
			}
		
	               
     }
} 
           
